In [1]:
import numpy as np

In [2]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
a = np.array([1, 2, 3]) 
print('a=', a)
b = np.array([1,2,1])
print('a.b =', np.dot(a,b))
print('a x b = ', np.outer(a,b))

ma = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('ma=',ma)
mzero = np.zeros((3,3))
print('mzero=',mzero)
mones = np.ones((3,3))
print('mones=', mones)
meye = np.eye(3)
print('meye=',meye)


a= [1 2 3]
a.b = 8
a x b =  [[1 2 1]
 [2 4 2]
 [3 6 3]]
ma= [[1 2 3]
 [4 5 6]
 [7 8 9]]
mzero= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
mones= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
meye= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
print('Some Matrix Multiplication')
m_element_element = ma*mones # Does element by element multiplication
print('Element by Element =', m_element_element)
m_matrix = np.matmul(ma,meye)
print('MatixMultiply =', m_matrix)
print('AlternateMatrixMultiple = ', meye@ma@meye)
print('size of ma =',ma.shape)


Some Matrix Multiplication
Element by Element = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
MatixMultiply = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
AlternateMatrixMultiple =  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
size of ma = (3, 3)


In [4]:
# Defining Linear Spaced Vector 
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html
start_point  = 0
stop_point = 10
n_points = 5
v_linear = np.linspace(start_point,stop_point, n_points)
print('v_linear=', v_linear)
# Define Log Spaced Vector
#start_point  = 1
#stop_point = 5
#n_points = 5
v_log = np.logspace(start_point,stop_point, n_points)
print('v_linear = ', v_log)


v_linear= [ 0.   2.5  5.   7.5 10. ]
v_linear =  [1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


In [5]:
# FlipLR and FlipUP in Python
a_ud = np.flipud(a)
a_ud
a_t = a.transpose()
print(a)
print(np.shape(a))
print(a_t)
print(np.shape(a_t))
print('print flipud(a) = ',np.flipud(a))
#a_lr =np.fliplr(np.transpose(a)) # Note if you try to flip on a unit dimension it fails
# Transpose does not convert a row vector into a colum vector. Hence the fliplr does not work for arrays of shape (N,)


[1 2 3]
(3,)
[1 2 3]
(3,)
print flipud(a) =  [3 2 1]


In [6]:
# Deleting Rows and Colums
# https://numpy.org/doc/1.18/reference/generated/numpy.delete.html
# Remember 0 refers to the 1st element of an array
ABCD = np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(ABCD)
print('ABCD(1,1) =', ABCD[0,0])
print('ABCD(1,1) =', ABCD[1,1])

test = np.delete(ABCD,1,0) # The last number is 0 for a row, 1 for a column or more importanly is the indice
print(test)


ABCD(1,1) = 1
ABCD(1,1) = 5
[[1 2 3]
 [7 8 9]]


In [7]:
# Subsituting Rows and Columns

# https://numpy.org/doc/1.18/reference/generated/numpy.all.html

# Substituting arrays is like Matlab remembering array indices start at 0
test = np.array([[1,2,3],[4,5,6],[7,8,9]])
#test_change = test.copy() 
test[0,:] = [0,2,0] # 1st row substiution
print(test)
test[:,0] = [0,2,0] # 1st column substitution
print(test)
test[1,1] =10 # Substiute a particular value
print(test)
print('test(1,1) =', test[1,1])


[[0 2 0]
 [4 5 6]
 [7 8 9]]
[[0 2 0]
 [2 5 6]
 [0 8 9]]
[[ 0  2  0]
 [ 2 10  6]
 [ 0  8  9]]
test(1,1) = 10
