# Data Science and Modelling

## 2 - Preliminaries

### Variables

#### Integers and Floats

In [1]:
# Declare an integer
intvar = 3
type(intvar)

int

In [2]:
# Declare a float
floatvar = 3.0
type(floatvar)

float

In [3]:
intvar + intvar

6

In [4]:
# Use scientific notation; use the print statement
scivar = 4.2e-20
print(scivar)

4.2e-20


In [5]:
# Arithmatic operations;
# Jupyter will display the output of the
# last executed line if there is any output to show
floatvar * intvar

9.0

In [6]:
floatvar + scivar

3.0

In [7]:
# Casting to an integer; rounds the value

int(3.7)

3

##### Exercise 2.1
What type is the product of an int and a float?

In [8]:
productvar = 3 * 2.0
type(productvar)

float

This is a float. Python typically casts to the more generic type when necessary.

##### Exercise 2.2

Which way does Python round?

In [9]:
print(int(3.7))
print(int(-4.6))

3
-4


Python always rounds towards zero. Positive numbers round down, negative numbers round up.

In [10]:
# Complex numbers; use j for the imaginary unit
# To define the number i, use 1j
complexvar = 2 + 3j

##### Exercise 2.3

What type is a complex number?

In [11]:
type(complexvar)

complex

This is its own datatype.

#### Strings

In [12]:
# Declare some strings; either single quotes ' or double quotes " will work

claresays = "Hello Barry"
barrysays = "Hello Clare"
print(claresays, barrysays)

Hello Barry Hello Clare


In [13]:
claresays + barrysays

'Hello BarryHello Clare'

##### Exercise 2.4

How do you define an empty string?

In [14]:
emptystring = ""

Just put quotes with no characters (not even a space) between. A space is still a character, and will give a string composed of just the space character.

##### Exercise 2.5

What is the name of the string type?

In [15]:
type(barrysays)

str

It is "str", not "string". 

#### Booleans

In [16]:
mybool = True
type(mybool)

bool

In [17]:
a = 4.5
b = 3.7
c = 145.6
a > b

True

##### Exercise 2.6

In [18]:
print(a > b)
print(c < b)
print(b < 0.0)

True
False
False


Are these correct?

##### Exercise 2.7

In [19]:
fruit1 = "Banana"
print(fruit1 == "Banana")
print(fruit1 != "Banana")
print(fruit1 < "Banana")
print(fruit1 > "Banana")

True
False
False
False


How can two strings be less than or greater than one another? An interesting question...

### Containers

#### Lists

In [20]:
mylist = [0, 1, 2, 3, "Bob"]
print(mylist)

[0, 1, 2, 3, 'Bob']


Lists can mix datatypes

##### Exercise 2.8

In [21]:
mylist[4]

'Bob'

Remember to count from zero

In [22]:
mynest = [0, ["x", "y", "z"]]
print(mynest[1][1])

y


##### Exercise 2.9

In [23]:
mynest[1][2]

'z'

##### Exercise 2.10

Change Bob to Anna

In [24]:
mylist

[0, 1, 2, 3, 'Bob']

In [25]:
mylist[4] = "Anna"
print(mylist)

[0, 1, 2, 3, 'Anna']


Lists are mutable, so they can change their elements after they've been created. 

Watch out! Be careful not to change a list if you will need its contents in the future.

##### Exercise 2.11

In [26]:
print(mylist)
print(len(mylist))

[0, 1, 2, 3, 'Anna']
5


In [27]:
zeroesgalore = [0.0] * 100
print(zeroesgalore)
print(len(zeroesgalore))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
100


In [28]:
numbers = [0.0, 2.0, 1.0, 3.0, 4.0, 5.0]
up = sorted(numbers)
print(up)
down = sorted(numbers, reverse=True)
print(down)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
[5.0, 4.0, 3.0, 2.0, 1.0, 0.0]


In [29]:
mixedlist = [["Beatles", 10], ["Hollies", 9], ["Herman's Hermits", 6], ["The Byrds", 7]]

Note the third element, using double quotes around the string allows using single quotes within. 

This also works the other way, 

In [30]:
string = 'Hello " World'
print(string)

Hello " World


In [31]:
sortedlist = sorted(mixedlist, key=lambda name: name[1])
print(sortedlist)

[["Herman's Hermits", 6], ['The Byrds', 7], ['Hollies', 9], ['Beatles', 10]]


This code relies on a lambda functional. These are small, simple function, that take in the arguments listed to the left of the colon, and return whatever is on the right.  These are good to know about but won't come up a lot for us.

In [32]:
adder = lambda a, b, c: a + b + c
adder(1, 2, 3)

6

#### Tuples

In [33]:
mytuple = (1, 2, 3)
print(mytuple)

(1, 2, 3)


In [34]:
mytuple[2] = 5

TypeError: 'tuple' object does not support item assignment

#### Dictionaries

In [35]:
dict = {"Name": "Barry", "Age": 40, "Job": "Plumber"}
print("The person's name: ", dict["Name"])
print("The person's age: ", dict["Age"])

The person's name:  Barry
The person's age:  40


In [36]:
dict["Age"] = 35
print(dict)

{'Name': 'Barry', 'Age': 35, 'Job': 'Plumber'}


##### Exercise 2.12

In [37]:
dict["Weight"] = 102
print(dict)

{'Name': 'Barry', 'Age': 35, 'Job': 'Plumber', 'Weight': 102}


### Indentation, loops, and conditional statements

In [38]:
for i in range(10):
    print("Counting to ten: ", i)

Counting to ten:  0
Counting to ten:  1
Counting to ten:  2
Counting to ten:  3
Counting to ten:  4
Counting to ten:  5
Counting to ten:  6
Counting to ten:  7
Counting to ten:  8
Counting to ten:  9


Note: the loop starts at zero, and ends one before the number we put in. Not many other languages are like this, many will include the end points. If you put 10 in, you will do 10 loops, but we start at 0, and so this happens.

Always remember that the loop will finish at N-1

In [39]:
for ientry in mixedlist:
    print("Band: ", ientry[0], "| Score: ", ientry[1])

Band:  Beatles | Score:  10
Band:  Hollies | Score:  9
Band:  Herman's Hermits | Score:  6
Band:  The Byrds | Score:  7


In [40]:
for i, ientry in enumerate(mixedlist):
    print("Counter: ", i, " | Band: ", ientry[0], " | Score: ", ientry[1])

Counter:  0  | Band:  Beatles  | Score:  10
Counter:  1  | Band:  Hollies  | Score:  9
Counter:  2  | Band:  Herman's Hermits  | Score:  6
Counter:  3  | Band:  The Byrds  | Score:  7


##### Exercise 2.13

In [41]:
for i, ientry in enumerate(sortedlist):
    print("Counter: ", i, " | Band: ", ientry[0], " | Score: ", ientry[1])

Counter:  0  | Band:  Herman's Hermits  | Score:  6
Counter:  1  | Band:  The Byrds  | Score:  7
Counter:  2  | Band:  Hollies  | Score:  9
Counter:  3  | Band:  Beatles  | Score:  10


In [42]:
# while loops

icecreams = ["magnum", "maxibon", "cornetto"]
count = 0
myicecream = "maxibon"
while count < 4:
    print(icecreams[count])
    if icecreams[count] != myicecream:
        count += 1
        continue
    print("I have found my icecream")
    break

magnum
maxibon
I have found my icecream


Flow Controls:

```continue``` jumps to the next iteration of the loop, without finishing the rest of the block

```break``` end the loop right there, and jumps to after the loop without finishing the remaining iterations

In [43]:
a = 1
if a == 1:
    print("a is 1")
elif a == 2:
    print("a is 2")
else:
    print("a is neither 1 or 2")

a is 1


#### List comprehension

In [44]:
sqrnumber = [i * i for i in range(20)]
print(sqrnumber)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


In [45]:
# only if i is odd

sqrnumber = [i * i for i in range(20) if i % 2 != 0]
print(sqrnumber)

[1, 9, 25, 49, 81, 121, 169, 225, 289, 361]


In [46]:
# ternary list comprehension

sqrnumber = [i * i if (i % 2 != 0) else "Even" for i in range(20)]
print(sqrnumber)

['Even', 1, 'Even', 9, 'Even', 25, 'Even', 49, 'Even', 81, 'Even', 121, 'Even', 169, 'Even', 225, 'Even', 289, 'Even', 361]


Note the difference in ordering for a conditional (... for ... if ...) vs. a ternary statement (... if ... else ... for ...)

##### Exercise 2.14

In [47]:
cube_even_numbers = [i**3 for i in range(60) if i % 2 == 0]
print(cube_even_numbers)
print(len(cube_even_numbers))

[0, 8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832, 8000, 10648, 13824, 17576, 21952, 27000, 32768, 39304, 46656, 54872, 64000, 74088, 85184, 97336, 110592, 125000, 140608, 157464, 175616, 195112]
30


Note the need to loop from 0 to 60 (not including the end point), as only half of these numbers are even, so we go double the distance to obtain the first 30 even cubes.

### Functions

In [48]:
def function_name(input):
    value = input + 1  # do some things here
    return value

##### Exercise 2.15

In [49]:
def printerFunction(input1, input2="default"):
    print(input1)
    # check if input2 is default or not
    if input2 == "default":
        print("I was not passed a second parameter")
    else:
        print("I was passed a second parameter, it was: ", input2)
    return "OK"

In [50]:
printerFunction("Hello", "World")

Hello
I was passed a second parameter, it was:  World


'OK'

In [51]:
printerFunction("Hello")

Hello
I was not passed a second parameter


'OK'

##### Exercise 2.16

In [52]:
def squareFunction(input):
    value = input**2
    return value

In [53]:
squareFunction(9)

81

##### Exercise 2.17

In [54]:
def square_cube(input, cube=False):
    if cube:
        return input**3
    else:
        return input**2

In [55]:
print(square_cube(9))
print(square_cube(9, False))
print(square_cube(9, True))

81
81
729


### Random Numbers

In [56]:
from random import seed, random, randint

seed(1)
for i in range(10):
    value = random()
    print(value)

0.13436424411240122
0.8474337369372327
0.763774618976614
0.2550690257394217
0.49543508709194095
0.4494910647887381
0.651592972722763
0.7887233511355132
0.0938595867742349
0.02834747652200631


##### Exercise 2.18

In [57]:
for i in range(10):
    value = random()
    print(value)

0.8357651039198697
0.43276706790505337
0.762280082457942
0.0021060533511106927
0.4453871940548014
0.7215400323407826
0.22876222127045265
0.9452706955539223
0.9014274576114836
0.030589983033553536


We get new numbers, as the random number generator continues from the previous state it was left at.

##### Exercise 2.19

In [58]:
seed(1)
for i in range(10):
    value = random()
    print(value)

0.13436424411240122
0.8474337369372327
0.763774618976614
0.2550690257394217
0.49543508709194095
0.4494910647887381
0.651592972722763
0.7887233511355132
0.0938595867742349
0.02834747652200631


We get the same numbers we got the first time. The state of the random number generator is reset to the same state it was in before the first generation. This allows us to have consistent results when using random numbers.

In [59]:
min = -2
max = 2
for i in range(10):
    value = random()
    scaled_value = min + (value * (max - min))
    print(scaled_value)

1.3430604156794788
-0.2689317283797865
1.049120329831768
-1.9915757865955572
-0.2184512237807943
0.8861601293631303
-1.0849511149181894
1.7810827822156892
1.6057098304459343
-1.8776400678657859


In [60]:
from random import gauss

for i in range(10):
    value = gauss(0, 1)
    print(value)

1.2327571750289237
0.1987912481934255
0.9090310261532091
-0.3655442662325168
0.21817181336058245
1.024288678487018
0.6962470224529616
0.1284722486328564
-1.0823080245960446
0.44522177236104854


### File input and output (I/O)

In [61]:
file1 = open("TestFile.txt", "w")
for i in range(1, 10 + 1):
    if i > 1:
        file1.write("\n")  # newline character
    file1.write(str(i))
file1.close()

In [62]:
with open("TestFile.txt", "r") as txt:
    for line in txt:
        print(line)

1

2

3

4

5

6

7

8

9

10


##### Exercise 2.20

In [63]:
file2 = open("TestFileGauss.txt", "w")
for i in range(1, 10 + 1):
    if i > 1:
        file2.write("\n")  # newline character
    value = gauss(0, 1)
    file2.write(str(value))
file2.close()

In [64]:
with open("TestFileGauss.txt", "r") as txt:
    for line in txt:
        print(line)

0.07686348171925232

0.7204675968592537

0.21623293780007305

1.0881854111355231

-0.051560265423925424

0.20196406007942128

0.6667764386256495

-1.0868846121744795

-0.4016602600740189

-0.5000285689523685


### Numpy (the best package there is)

In [65]:
import numpy as np

mylist = [0, 1, 2, 3, 4]
myarray = np.array(mylist)

In [66]:
mylist + 2

TypeError: can only concatenate list (not "int") to list

In [67]:
myarray + 2

array([2, 3, 4, 5, 6])

##### Exercise 2.21

In [68]:
myarray = np.array([0, 10, 20, 30])
newarray = myarray + 10
print(newarray)

[10 20 30 40]


In [76]:
list2d = [[0, 1, 2], 
          [3, 4, 5], 
          [6, 7, 8]]
array2d = np.array(list2d)
print(array2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [70]:
array2d = np.array(list2d, dtype="float")
print(array2d)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


##### Exercise 2.22

In [71]:
print("Shape: ", array2d.shape)
print("Size: ", array2d.size)
print("Num Dimensions: ", array2d.ndim)

Shape:  (3, 3)
Size:  9
Num Dimensions:  2


In [72]:
array2d[:2, :2]

array([[0., 1.],
       [3., 4.]])

In [73]:
array2d.flatten()

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [74]:
print(np.zeros([2, 2]))
print(np.ones([2, 2]))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [75]:
# Create a random state object with a given seed
rn = np.random.RandomState(100)

# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2, 2))

# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2, 2))

# Make a numpy array with 1000 Gaussian random numbers in, with mean mu and
# standard deviation sigma
mu = 5
sigma = 2
s = np.random.normal(mu, sigma, 1000)

# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2, 2))

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2, 2]))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]
[[0.69564545 0.86142567]
 [0.25288984 0.43629151]]
[[ 0.41517093  0.55490644]
 [-1.4640506  -0.34350368]]
[[7 5]
 [2 5]]
